export const WIDGET_SOURCE_WIDTH = 704;
export const WIDGET_SOURCE_HEIGHT = 304;
export const WIDGET_COMPOSITION_SCALE = 0.91;
export const WIDGET_RENDER_WIDTH = Math.round(WIDGET_SOURCE_WIDTH * WIDGET_COMPOSITION_SCALE);
export const WIDGET_RENDER_HEIGHT = Math.round(WIDGET_SOURCE_HEIGHT * WIDGET_COMPOSITION_SCALE);
export const CONTROL_DECK_SOURCE_HEIGHT = 42;
export const CONTROL_DECK_GAP = 2;
export const CONTROL_DECK_RENDER_HEIGHT = Math.ceil(
  (CONTROL_DECK_SOURCE_HEIGHT + CONTROL_DECK_GAP) * WIDGET_COMPOSITION_SCALE,
);
